repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: ""
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/asottile/pyupgrade
    rev: ""
    hooks:
      - id: pyupgrade
        args: [--py312-plus]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: ""
    hooks:
      - id: ruff-format
  - repo: https://github.com/PyCQA/isort
    rev: ""
    hooks:
      - id: isort
  - repo: https://github.com/DetachHead/basedpyright-pre-commit-mirror
    rev: ""
    hooks:
      - id: basedpyright
        #: if cookiecutter.module_type == "bin"
        additional_dependencies: ["typer>=0.15.1"]
        #: else
        additional_dependencies: []
        #: endif
