repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: ""
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: ""
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: ""
    hooks:
      - id: isort
