repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: ""
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: ""
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: ""
    hooks:
      - id: isort
  - repo: local
    hooks:
      # shoutout to https://github.com/RobertCraigie/pyright-python
      - id: pyright
        name: pyright
        description: "Python command line wrapper for pyright, a static type checker"
        entry: basedpyright
        language: python
        "types_or": [python]
        require_serial: true
        additional_dependencies: ["genanki", "pydantic", "black", "typer"]
        minimum_pre_commit_version: "2.9.2"
